{
 "title": "Addressbook",
 "time": { "from": "2026-03-29T23:09:15.567Z", "to": "2026-03-30T23:09:15.567Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU seconds of user and system",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode=\"user\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "\nrate(node_cpu_seconds_total{mode=\"system\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App Threads Count",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AddressBook CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total[1m])",
     "legendFormat": "__auto"
    },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "AddressBook Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "__auto"
    },
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "AddressBook App Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "up{job=\"addressbook-service\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}