apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: addressbook-monitor
  labels:
    release: monitoring

spec:
  selector:
    matchLabels:
      app: addressbook

  namespaceSelector:
    matchNames:
      - default

  endpoints:
    - port: metrics
      path: /metrics
      interval: 5s