grafana:
  service:
    type: NodePort
    nodePort: 30009

  sidecar:
    dashboards:
      enabled: true

  dashboards:
    default:
      addressbook:
        file: dashboard.json    

  adminUser: admin
  adminPassword: "admin123"


prometheus:
  service:
    type: NodePort
    nodePort: 30008


# helm get values monitoring -n monitoring
# to auto load dash