apiVersion: v1
kind: Service
metadata:
  name: addressbook-service
  labels:
    app: addressbook   

spec:
  type: NodePort
  selector:
    app: addressbook

  ports:
    - name: http       
      port: 8080
      targetPort: 8080
      nodePort: 30007

    - name: metrics
      port: 9100
      targetPort: 9100