plugin: amazon.aws.aws_ec2

regions:
  - us-east-1

filters:
  "tag:Roles": "app-server"

hostnames:
  - public-dns-name

keyed_groups:
  - key: tags.Name
    prefix: server

compose:
  ansible_host: public_ip_address
  #ansible_host: public_dns_name
  ansible_user: ubuntu
  #ansible_ssh_private_key_file: "'/Users/jagdish/Downloads/devops-final.pem'"
  ansible_ssh_private_key_file: "{{ lookup('env','PEM_FILE') }}"