---
- name: Docker-Pipeline
  hosts: all
  become: yes

  vars:
    docker_image_name: myapp
    docker_container_name: myapp_container

  tasks:
  
  - name: Gather package facts
    package_facts:
      manager: auto

  - name: Install Docker only if not present
    apt:
      name: docker.io
      state: present
    when: ansible_facts.packages['docker.io'] is not defined

  - name: Start Docker service
    service:
      name: docker
      state: started
      enabled: true

  - name: Copy WAR file to server
    copy:
      src: ../target/addressbook.war
      #src: /Users/jagdish/Documents/DevOpsClassCodes/addressbook.war
      dest: /tmp/addressbook.war

  - name: Remove old container
    docker_container:
      name: "{{ docker_container_name }}"
      state: absent
      force_kill: yes

  - name: Remove old image
    docker_image:
      name: "{{ docker_image_name }}"
      state: absent

  - name: Run Docker container
    docker_container:
      name: "{{ docker_container_name }}"
      image: tomcat:9-jdk17
      state: started
      restart_policy: always
      ports:
        - "8080:8080"
      volumes:
        - "/tmp/addressbook.war:/usr/local/tomcat/webapps/addressbook.war"

  - name: Access URL
    debug:
      msg: "Server {{ inventory_hostname }} → http://{{ ansible_host }}:8080/addressbook"